const ACTIONS = {
  ADD_BOOKMARK: "ADD_BOOKMARK",
  REMOVE_BOOKMARK: "REMOVE_BOOKMARK",
  GET_BOOKMARKS: "GET_BOOKMARKS",
  SIGN_IN: "SIGN_IN",
  SIGN_UP: "SIGN_UP",
  UPDATE_USER: "UPDATE_USER",
};

module.exports = { ACTIONS };
